# Generated by Django 4.2.2 on 2023-06-10 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Узел отказа',
                'verbose_name_plural': '_СПРАВОЧНИК_Узлы отказа',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид Технического Обслуживания',
                'verbose_name_plural': '_СПРАВОЧНИК_Виды Технического Обслуживания',
            },
        ),
        migrations.CreateModel(
            name='ModelDriveAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
                'verbose_name_plural': '_СПРАВОЧНИК_Модели ведущего моста',
            },
        ),
        migrations.CreateModel(
            name='ModelEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
                'verbose_name_plural': '_СПРАВОЧНИК_Модели двигателя',
            },
        ),
        migrations.CreateModel(
            name='ModelMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель техники',
                'verbose_name_plural': '_СПРАВОЧНИК_Модели техники',
            },
        ),
        migrations.CreateModel(
            name='ModelSteeringAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
                'verbose_name_plural': '_СПРАВОЧНИК_Модели управляемого моста',
            },
        ),
        migrations.CreateModel(
            name='ModelTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
                'verbose_name_plural': '_СПРАВОЧНИК_Модели трансмиссии',
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
                'verbose_name_plural': '_СПРАВОЧНИК_Способы восстановления',
            },
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сервисная компания',
                'verbose_name_plural': '_СПРАВОЧНИК_Сервисные компании',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenanceDate', models.DateField(verbose_name='Дата проведения ТО')),
                ('operatingTime', models.IntegerField(verbose_name='Наработка, м/час')),
                ('workOrder', models.CharField(max_length=255, verbose_name='№ заказ-наряда')),
                ('workOrderDate', models.DateField(verbose_name='Дата заказ-наряда')),
                ('executor', models.CharField(max_length=255, verbose_name='Организация, проводившая ТО')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.modelmachine', verbose_name='Машина')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.servicecompany', verbose_name='Сервисная компания')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenanceTypes', to='crm_app.maintenancetype', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'ТЕХНИЧЕСКОЕ ОБСЛУЖИВАНИЕ',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=255, verbose_name='Зав. № машины')),
                ('serialNumberEngine', models.CharField(max_length=255, verbose_name='Зав. № двигателя')),
                ('serialTransmission', models.CharField(max_length=255, verbose_name='Зав. № трансмиссии')),
                ('serialDriveAxle', models.CharField(max_length=255, verbose_name='Зав. № ведущего моста')),
                ('serialSteeringAxle', models.CharField(max_length=255, verbose_name='Зав. № управляемого моста')),
                ('deliveryContract', models.CharField(max_length=255, verbose_name='Договор поставки №, дата')),
                ('shipmentDate', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=255, verbose_name='Грузополучатель (конечный потребитель)')),
                ('deliveryAddress', models.CharField(max_length=255, verbose_name='Адрес поставки (эксплуатации)')),
                ('additionalOptions', models.TextField(default='Комплектация не указана', verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('modelDriveAxle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelDriveAxles', to='crm_app.modeldriveaxle', verbose_name='Модель ведущего моста')),
                ('modelEngine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelEngines', to='crm_app.modelengine', verbose_name='Модель двигателя')),
                ('modelMachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelMachines', to='crm_app.modelmachine', verbose_name='Модель техники')),
                ('modelSteeringAxle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelSteeringAxles', to='crm_app.modelsteeringaxle', verbose_name='Модель управляемого моста')),
                ('modelTransmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelTransmissions', to='crm_app.modeltransmission', verbose_name='Модель трансмиссии')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.servicecompany', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'МАШИНЫ',
            },
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakdownDate', models.DateField(verbose_name='Дата отказа')),
                ('operatingTime', models.IntegerField(verbose_name='Наработка, м/час')),
                ('breakdownDescription', models.TextField(verbose_name='Описание отказа')),
                ('usedSpareParts', models.TextField(verbose_name='Используемые запасные части')),
                ('recoverDate', models.DateField(verbose_name='Дата восстановления')),
                ('downtime', models.IntegerField(verbose_name='Время простоя техники')),
                ('breakdownNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='crm_app.breakdown', verbose_name='Узел отказа')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.modelmachine', verbose_name='Mашина')),
                ('recoveryMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveryMethods', to='crm_app.recoverymethod', verbose_name='Способ восстановления')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.servicecompany', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'РЕКЛАМАЦИИ',
            },
        ),
    ]
