# Generated by Django 4.2.2 on 2023-06-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='serialDriveAxle',
            field=models.CharField(max_length=255, unique=True, verbose_name='Зав. № ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serialNumber',
            field=models.CharField(max_length=255, unique=True, verbose_name='Зав. № машины'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serialNumberEngine',
            field=models.CharField(max_length=255, unique=True, verbose_name='Зав. № двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serialSteeringAxle',
            field=models.CharField(max_length=255, unique=True, verbose_name='Зав. № управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serialTransmission',
            field=models.CharField(max_length=255, unique=True, verbose_name='Зав. № трансмиссии'),
        ),
    ]
