# Generated by Django 4.2.2 on 2023-07-08 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_alter_machine_serialdriveaxle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.machine', verbose_name='Зав. № машины'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.machine', verbose_name='Зав. № машины'),
        ),
    ]
